### ISSUE TITLE
Enlever le champ "Numéro de la saison" de la bdd des épisodes.

### ISSUE THREAD

**Issue by eliott-lumet** [purerstamp/CPS-grand-tournoi#11]
Il n'y a pas de numérotation officielle des épisodes. 
Je propose donc de retirer le champ "saison" qui correspond au "Numéro de la saison" dans le modèle de la base de données des épisodes.

> /siteweb/listing/models.py

_En fait les saisons sont équivalentes aux catégories dans les coffrets DVD et sur Youtube_

**Comment by purerstamp** [comment]
Corrigé avec 396653f175246f48c9b68b7b99b46c6eb67be1fd
