### ISSUE TITLE
Format de date incohérent entre CSV et BDD

### ISSUE THREAD

**Issue by purerstamp** [purerstamp/CPS-grand-tournoi#12]
Afin de bénéficier facilement de fonctionnalités de tri et classements par date ou ordre chronologique sur le site web, le champ date en bdd a été créé avec le type _DateField_ (python _datetime.date_).

Le format attendu est AAAA-MM-JJ. Le format dans le fichier de données est JJ/MM/AA.

Deux solutions : 

- faire correspondre le format attendu à celui choisi dans le CSV (**si le format attendu peut être modifié**)
- faire correspondre le format en CSV au format en BDD

Ce bug a été découvert à l'exécution des tests pour l'application _listing_.
![Capture d’écran de 2020-12-18 12-13-17](https://user-images.githubusercontent.com/17382504/102608639-78707580-412a-11eb-8c8a-2dd68c5a9197.png)

**Comment by purerstamp** [comment]
[Il semblerait](https://stackoverflow.com/questions/30911612/how-can-i-set-a-datefield-format-in-django-from-the-model) que la première option soit possible, étant donné que la contrainte ne se situe pas dans le modèle mais dans la vue. En revanche, le commentaire suivant me chiffone : 

> This will only work if USE_L10N is False. You may also need to set DATE_FORMAT used when printing a date in the templates.

C'est un paramètre qui permet de gérer automatiquement l'internationalisation des formats de nombres, dates, heures etc. Ceci remet en cause nos ambitions de développement à l'international. En effet, en désactivant USE_L10N, le format par défaut sera le format unique défini (français).

**Comment by eliott-lumet** [comment]
J'ai modifié le format de la date dans le fichier .csv, je ne peux pas encore tester si ça a solutionné le problème.

**Comment by purerstamp** [comment]
Corrigé par 1cec4e3f8f38e63942b8a0f5509e1e93b45584fe. Les tests sont OK. **Penser à annuler les changements via git lorsque les tests sont lancés afin de rétablir la base de données à sa version précédente (vide pour le moment).**
